Library/Controllers/BookController.cs
using LibrarySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.IdentityModel.Tokens;
using System.Linq;
using LibrarySystem.Data;
using Microsoft.AspNetCore.Authorization;

namespace LibrarySystem.Controllers
{
    [Authorize(Roles= "Admin")]
    public class BookController : Controller

    {


        private ApplicationDbContext _db;
        private IWebHostEnvironment _webHostEnvironment;

        public BookController(ApplicationDbContext db,IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }
       
     


    public IActionResult Index()


        {
            IEnumerable<BookModel> data = _db.Books
                .Include(u => u.Category)
                .ToList();


           





            return View(data);
        }
        [Authorize(Roles = "Admin")]

        [HttpGet]
        public IActionResult BookAdd()
        {

            List<string> status = new List<string>()
            {

                "Available",
                "Not Available"
            };

            

            ViewBag.Status = status;

            IEnumerable<SelectListItem> CategoryList = _db.Categories.Select(u => new SelectListItem
            {
                Text = u.CategoryName,
                Value = u.Id.ToString()
                
            });

            ViewBag.CategoryList = CategoryList;

            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult BookAdd(BookModel obj, IFormFile? file)
        {

            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                var BookPath = Path.Combine(wwwRootPath, @"Images\Books");

                using (var filestream = new FileStream(Path.Combine(BookPath, fileName), FileMode.Create))
                {
                    file.CopyTo(filestream);

                };
                obj.ImageUrl = @"\Images\Books\" + fileName;
            }

            _db.Books.Add(obj);
            _db.SaveChanges();


            return RedirectToAction("Index");
        }

   

    [Authorize(Roles ="Admin")]

    [HttpGet]
    public IActionResult BookEdit(int id)
    {

            List<string> status = new List<string>()
            {

                "Available",
                "Not Available"
            };

            ViewBag.Status = status;

            var data=_db.Books.FirstOrDefault(u=>u.Id==id);

            IEnumerable<SelectListItem> CategoryList = _db.Categories.Select(u => new SelectListItem
            {
                Text = u.CategoryName,
                Value = u.Id.ToString()

            });

            
            ViewBag.CategoryList = CategoryList;



            return View(data);
    }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        
        public IActionResult BookEdit(BookModel obj,IFormFile? file)

        {

            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if(file != null)
            {
                string fileName=Guid.NewGuid().ToString()+ Path.GetExtension(file.FileName);
                var BookPath=Path.Combine(wwwRootPath, @"Images\Books");
                if (!string.IsNullOrEmpty(obj.ImageUrl))
                {
                    //deleting of old image
                    var oldImagePath = Path.Combine(wwwRootPath, obj.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var filestream = new FileStream(Path.Combine(BookPath, fileName),FileMode.Create))
                {
                    file.CopyTo(filestream);
                    
                } ;
                obj.ImageUrl = @"\Images\Books\"+fileName;
            }

            _db.Update(obj);
            _db.SaveChanges();



            return RedirectToAction("Index");   
                }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult BookDelete(int? id)
        {
            var data = _db.Books.FirstOrDefault(u=>u.Id == id);





            return View(data);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult BookDelete(BookModel obj)
        {
            _db.Books.Remove(obj);
            _db.SaveChanges();





            return RedirectToAction("Index");
        }

    }



}

Library/Controllers/CategoryController.cs
using LibrarySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LibrarySystem.Data;
using Microsoft.AspNetCore.Authorization;

namespace LibrarySystem.Controllers
{

    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()


        {
            var data = _db.Categories.ToList();
            return View(data);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult CategoryAdd()


        {

            return View();

        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult CategoryAdd(CategoryModel obj)


        {
            _db.Categories.Add(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult CategoryEdit(int id)


        {

            var data=_db.Categories.FirstOrDefault(c => c.Id == id);
            return View(data);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult CategoryEdit(CategoryModel obj)


        {
            _db.Categories.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult CategoryDelete(int? id)


        {
            var data = _db.Categories.FirstOrDefault(c => c.Id == id);
            return View(data);
        }

        [Authorize(Roles ="Admin")]
        [HttpPost]
        public IActionResult CategoryDelete(CategoryModel obj)


        {
            _db.Categories.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Library/Controllers/UsersController.cs
using Library.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{

    [Authorize(Roles = "Admin")]
    public class UsersController:Controller
    {


        private readonly UserManager<AppUser> _userManager;

        public UsersController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;

        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var data=_userManager.Users;
            return View(data);
        }

    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Library</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="lib" rel="icon">
    <link href="~/lib/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/lib/quill/quill.snow.css" rel="stylesheet">
    <link href="~/lib/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/lib/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/lib/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="/css/style.css" rel="stylesheet">

   
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a asp-controller="Book" asp-action="Index" class="logo d-flex align-items-center">
                <img src="~/lib/img/logo1.png" alt="">
                <span class="d-none d-lg-block">Library Admin</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="d-none d-lg-inline-block me-lg-3 mb-3 mb-md-0" href="#">Welcome @User.Identity.Name !</a>

                    <a class="btn btn-secondary  d-none d-lg-inline-block me-lg-3 mb-3 mb-md-0" asp-controller="Account" asp-action="Logout">Logout</a>
                    
                }


               

                   

                   


            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a asp-controller="Category" asp-action="Index" class="nav-link collapsed">
                    <i class="bi bi-grid"></i>
                    <span>Category</span>
                </a>



            </li>
            


            <li class="nav-item ">
                <a asp-controller="Book" asp-action="Index" class="nav-link collapsed">
                    <i class="bi bi-book"></i>
                    <span>Book</span>
                </a>
                </li>


          


          



            <li class="nav-item ">
                <a asp-controller="Users" asp-action="Index" class="nav-link collapsed">
                    <i class="bi bi-person-gear"></i>
                    <span>Users</span>
                </a>


            </li>



           


        </ul>

    </aside><!-- End Sidebar-->

    <main id="main" class="main">

       

        <section class="section ">
            <div class="row">
                
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>

                
            </div>
        </section>

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
       
      
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    










    

       






   

    
          
        
    <!-- Vendor JS Files -->

    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/chart.js/chart.umd.js"></script>
    <script src="~/lib/echarts/echarts.min.js"></script>
    <script src="~/lib/quill/quill.min.js"></script>
    <script src="~/lib/simple-datatables/simple-datatables.js"></script>
    <script src="~/lib/tinymce/tinymce.min.js"></script>
    <script src="~/lib/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>
    
  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Library/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Library-Home</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="lib" rel="icon">
    <link href="~/lib/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/lib/quill/quill.snow.css" rel="stylesheet">
    <link href="~/lib/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/lib/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/lib/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="/css/style.css" rel="stylesheet">

</head>

<body class="toggle-sidebar">

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class=" align-items-center justify-content-between">
            <a asp-controller="Home" asp-action="Index" class="logo align-items-center">
                <img src="~/lib/img/logo1.png" alt="">
                <span style=" margin-right:30px;">Library</span>
            </a>
            
        </div><!-- End Logo -->

        <div class=" nav-item align-items-center justify-content-between">
            <a asp-controller="Home" asp-action="Index" class=" nav-link d-flex align-items-center">

                <span class="  d-none d-lg-block ">Home</span>
            </a>

          


           


        </div><!-- End Home Anchor -->
        @if (User.IsInRole("Admin"))
        {

            

       
            <div class=" nav-item align-items-center justify-content-between">
                <a class="nav-link d-flex align-items-center ms-4" asp-controller="Book" asp-action="Index">Admin Dashboard</a>
            </div>





            
        }



     
       

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->

               



                @if (!User.Identity.IsAuthenticated)
                {
                    <a class="btn btn-secondary d-none d-lg-inline-block me-lg-2 mb-3 mb-md-0" asp-controller="Account" asp-action="Login">Login</a>
                    <a class="btn btn-secondary  d-none d-lg-inline-block me-lg-3 mb-3 mb-md-0" asp-controller="Account" asp-action="Register">Register</a>
                }

                else
                {
                    <a class="d-none d-lg-inline-block me-lg-3 mb-3 mb-md-0" href="#">Welcome @User.Identity.Name !</a>

                    <a class="btn btn-dark  d-none d-lg-inline-block me-lg-3 mb-3 mb-md-0" asp-controller="Account" asp-action="Logout">Logout</a>
                }




        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->
   
    


    <main id="main" class="mx-5  ">



        <section class="section ">
            <div class="row">

                <main role="main" class="pb-3">
                    @RenderBody()
                </main>


            </div>
        </section>

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
       
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


























    <!-- Vendor JS Files -->

    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/chart.js/chart.umd.js"></script>
    <script src="~/lib/echarts/echarts.min.js"></script>
    <script src="~/lib/quill/quill.min.js"></script>
    <script src="~/lib/simple-datatables/simple-datatables.js"></script>
    <script src="~/lib/tinymce/tinymce.min.js"></script>
    <script src="~/lib/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>